Script started on Mon 07 Mar 2016 05:15:49 PM EST

PLAY ***************************************************************************

TASK [setup] *******************************************************************
[0;31mfatal: [hnbaixmon.kdc.capitalone.com]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}[0m
[0;31mfatal: [normandy.kdc.capitalone.com]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}[0m
[0;31mfatal: [sd2n2v4.kdc.capitalone.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "3431.1 Security error, please see your administrator.\r\npbrun6.2.0-09[28508]: Could not connect to run host sd2n2v4.kdc.capitalone.com\n", "msg": "MODULE FAILURE", "parsed": false}[0m
[0;32mok: [aquifer664.kdc.capitalone.com][0m
[0;31mfatal: [icebird.kdc.capitalone.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "  File \"/home/aaa/.ansible/tmp/ansible-tmp-1457388949.74-221473104226139/setup\", line 360\r\n    return dict((_convert(k), _convert(v)) for k, v in node.items())\r\n                                             ^\r\nSyntaxError: invalid syntax\r\n", "msg": "MODULE FAILURE", "parsed": false}[0m
[0;31mfatal: [cruise.kdc.capitalone.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "ERROR:root:code for hash md5 was not found.\r\nTraceback (most recent call last):\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 139, in <module>\r\n    globals()[__func_name] = __get_hash(__func_name)\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 91, in __get_builtin_constructor\r\n    raise ValueError('unsupported hash type ' + name)\r\nValueError: unsupported hash type md5\r\nERROR:root:code for hash sha1 was not found.\r\nTraceback (most recent call last):\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 139, in <module>\r\n    globals()[__func_name] = __get_hash(__func_name)\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 91, in __get_builtin_constructor\r\n    raise ValueError('unsupported hash type ' + name)\r\nValueError: unsupported hash type sha1\r\nERROR:root:code for hash sha224 was not found.\r\nTraceback (most recent call last):\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 139, in <module>\r\n    globals()[__func_name] = __get_hash(__func_name)\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 91, in __get_builtin_constructor\r\n    raise ValueError('unsupported hash type ' + name)\r\nValueError: unsupported hash type sha224\r\nERROR:root:code for hash sha256 was not found.\r\nTraceback (most recent call last):\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 139, in <module>\r\n    globals()[__func_name] = __get_hash(__func_name)\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 91, in __get_builtin_constructor\r\n    raise ValueError('unsupported hash type ' + name)\r\nValueError: unsupported hash type sha256\r\nERROR:root:code for hash sha384 was not found.\r\nTraceback (most recent call last):\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 139, in <module>\r\n    globals()[__func_name] = __get_hash(__func_name)\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 91, in __get_builtin_constructor\r\n    raise ValueError('unsupported hash type ' + name)\r\nValueError: unsupported hash type sha384\r\nERROR:root:code for hash sha512 was not found.\r\nTraceback (most recent call last):\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 139, in <module>\r\n    globals()[__func_name] = __get_hash(__func_name)\r\n  File \"/opt/freeware/lib/python2.7/hashlib.py\", line 91, in __get_builtin_constructor\r\n    raise ValueError('unsupported hash type ' + name)\r\nValueError: unsupported hash type sha512\r\nTraceback (most recent call last):\r\n  File \"/home/aaa/.ansible/tmp/ansible-tmp-1457388951.22-171852650198480/setup\", line 320, in <module>\r\n    AVAILABLE_HASH_ALGORITHMS[algorithm] = getattr(hashlib, algorithm)\r\nAttributeError: 'module' object has no attribute 'md5'\r\n", "msg": "MODULE FAILURE", "parsed": false}[0m
[0;31mfatal: [janie.kdc.capitalone.com]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}[0m
[0;32mok: [hurley.kdc.capitalone.com][0m
[0;31mfatal: [nigel2.kdc.capitalone.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "3431.1 Security error, please see your administrator.\r\npbrun6.2.0-09[25545]: Could not connect to run host nigel2.kdc.capitalone.com\n", "msg": "MODULE FAILURE", "parsed": false}[0m
[0;31mfatal: [kdcnim01.kdc.capitalone.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "  File \"/home/aaa/.ansible/tmp/ansible-tmp-1457388953.07-281411957864176/setup\", line 360\r\n    return dict((_convert(k), _convert(v)) for k, v in node.items())\r\n                                             ^\r\nSyntaxError: invalid syntax\r\n", "msg": "MODULE FAILURE", "parsed": false}[0m
[0;31mfatal: [stealth.kdc.capitalone.com]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}[0m
[0;31mfatal: [plmcduck.kdc.capitalone.com]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}[0m
[0;31mfatal: [pdcjumpstart.kdc.capitalone.com]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}[0m
[0;31mfatal: [devcaps01.kdc.capitalone.com]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}[0m
[0;32mok: [radius.kdc.capitalone.com][0m
[0;31mfatal: [utah.kdc.capitalone.com]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}[0m
[0;31mfatal: [kdcinfo.kdc.capitalone.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "\r\n ... pbrun is depreciated .. you should be using the new Centrify tool - 'dzdo' instead . \r\n\r\n ... Syntax for dzdo is 'dzdo -u <Effective.user> <command>' \r\n\r\n ... Example:- 'dzdo -u ddebatch cat /prod/users/ddebatch/file1' \r\n\r\n ... to check what elevated commands you have access to, execute 'dzdo -l' \r\n\r\n ... For more information, please visit the pulse page -> https://pulse.kdc.capitalone.com/docs/DOC-129371 \r\n\r\n ... redirecting to dzdo ... \r\n\r\n ... executing /usr/bin/dzdo -u root -b -l -u root /usr/bin/python /home/aaa/.ansible/tmp/ansible-tmp-1457388958.46-215992900492651/setup  \r\ndzdo: you may not specify both the `-l' option and [command]\r\nusage: dzdo -K | -k | -V\r\nusage: dzdo -v [-AknS] [-g groupname|#gid] [-p prompt] [-u username|#uid]\r\nusage: dzdo -l[l] [-AknS] [-g groupname|#gid] [-p prompt] [-u username|#uid]\r\n            [command]\r\nusage: dzdo [-AbHknPS] [-C num] [-g groupname|#gid] [-p prompt] [-u\r\n            username|#uid] [VAR=value] [-i|-s] [<command>]\r\nusage: dzdo -e [-AknS] [-C num] [-g groupname|#gid] [-p prompt] [-u\r\n            username|#uid] file ...\r\nusage: dzdo -h [user@]<host> [-W,ssh-option] <arguments>\r\nusage: dzdo --help\r\n", "msg": "MODULE FAILURE", "parsed": false}[0m
[0;31mfatal: [drdns1.kdc.capitalone.com]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}[0m
[0;31mfatal: [bourne.kdc.capitalone.com]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}[0m
[0;31mfatal: [drdns2.kdc.capitalone.com]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}[0m

TASK [Manage authorized_keys for all users] ************************************
[0;32mok: [aquifer664.kdc.capitalone.com] => (item=dqg168)[0m
[0;31mfailed: [hurley.kdc.capitalone.com] => (item=dqg168) => {"failed": true, "item": "dqg168", "msg": "Failed to lookup user dqg168: 'getpwnam(): name not found: dqg168'"}[0m
[0;31mfailed: [radius.kdc.capitalone.com] => (item=dqg168) => {"failed": true, "item": "dqg168", "msg": "Failed to lookup user dqg168: 'getpwnam(): name not found: dqg168'"}[0m

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
[0;32maquifer664.kdc.capitalone.com[0m : [0;32mok[0m[0;32m=[0m[0;32m2[0m    changed=0    unreachable=0    failed=0   
[0;31mbourne.kdc.capitalone.com[0m  : ok=0    changed=0    [0;31munreachable[0m[0;31m=[0m[0;31m1[0m    failed=0   
[0;31mcruise.kdc.capitalone.com[0m  : ok=0    changed=0    unreachable=0    [0;31mfailed[0m[0;31m=[0m[0;31m1[0m   
[0;31mdevcaps01.kdc.capitalone.com[0m : ok=0    changed=0    [0;31munreachable[0m[0;31m=[0m[0;31m1[0m    failed=0   
[0;31mdrdns1.kdc.capitalone.com[0m  : ok=0    changed=0    [0;31munreachable[0m[0;31m=[0m[0;31m1[0m    failed=0   
[0;31mdrdns2.kdc.capitalone.com[0m  : ok=0    changed=0    [0;31munreachable[0m[0;31m=[0m[0;31m1[0m    failed=0   
[0;31mhnbaixmon.kdc.capitalone.com[0m : ok=0    changed=0    [0;31munreachable[0m[0;31m=[0m[0;31m1[0m    failed=0   
[0;31mhurley.kdc.capitalone.com[0m  : [0;32mok[0m[0;32m=[0m[0;32m1[0m    changed=0    unreachable=0    [0;31mfailed[0m[0;31m=[0m[0;31m1[0m   
[0;31micebird.kdc.capitalone.com[0m : ok=0    changed=0    unreachable=0    [0;31mfailed[0m[0;31m=[0m[0;31m1[0m   
[0;31mjanie.kdc.capitalone.com[0m   : ok=0    changed=0    [0;31munreachable[0m[0;31m=[0m[0;31m1[0m    failed=0   
[0;31mkdcinfo.kdc.capitalone.com[0m : ok=0    changed=0    unreachable=0    [0;31mfailed[0m[0;31m=[0m[0;31m1[0m   
[0;31mkdcnim01.kdc.capitalone.com[0m : ok=0    changed=0    unreachable=0    [0;31mfailed[0m[0;31m=[0m[0;31m1[0m   
[0;31mnigel2.kdc.capitalone.com[0m  : ok=0    changed=0    unreachable=0    [0;31mfailed[0m[0;31m=[0m[0;31m1[0m   
[0;31mnormandy.kdc.capitalone.com[0m : ok=0    changed=0    [0;31munreachable[0m[0;31m=[0m[0;31m1[0m    failed=0   
[0;31mpdcjumpstart.kdc.capitalone.com[0m : ok=0    changed=0    [0;31munreachable[0m[0;31m=[0m[0;31m1[0m    failed=0   
[0;31mplmcduck.kdc.capitalone.com[0m : ok=0    changed=0    [0;31munreachable[0m[0;31m=[0m[0;31m1[0m    failed=0   
[0;31mradius.kdc.capitalone.com[0m  : [0;32mok[0m[0;32m=[0m[0;32m1[0m    changed=0    unreachable=0    [0;31mfailed[0m[0;31m=[0m[0;31m1[0m   
[0;31msd2n2v4.kdc.capitalone.com[0m : ok=0    changed=0    unreachable=0    [0;31mfailed[0m[0;31m=[0m[0;31m1[0m   
[0;31mstealth.kdc.capitalone.com[0m : ok=0    changed=0    [0;31munreachable[0m[0;31m=[0m[0;31m1[0m    failed=0   
[0;31mutah.kdc.capitalone.com[0m    : ok=0    changed=0    [0;31munreachable[0m[0;31m=[0m[0;31m1[0m    failed=0   


Script done on Mon 07 Mar 2016 05:16:09 PM EST
